### ISSUE TITLE
Snack expo example

### ISSUE THREAD

**Issue by Angelk90** [breeffy/react-native-monorepo#39]
Hi @likern , would it be possible to create an example that I could run directly on https://snack.expo.io?

**Comment by likern** [comment]
> Hi @likern , would it be possible to create an example that I could run directly on https://snack.expo.io?

Hello 👋 Yes, I think it would be possible. But I have no experience with snack or expo. I suggest it requires manual copy-pasting.

Anyway, PR with this support will be welcomed.

**Comment by Angelk90** [comment]
@likern : I did a test, but there seems to be problems, try to check it out.
Link: https://snack.expo.io/wheba34vh

**Comment by likern** [comment]
> @likern : I did a test, but there seems to be problems, try to check it out.
> Link: https://snack.expo.io/wheba34vh

I think it's missing files.

**Comment by Angelk90** [comment]
@likern : I noticed it too, but I don't understand when I clone the project or download it directly missing folders and files such as the file, `'./components/appearanceProvider'.`
Very strange, but I get it from the latest version in the main branch.

**Comment by likern** [comment]
> @likern : I noticed it too, but I don't understand when I clone the project or download it directly missing folders and files such as the file, `'./components/appearanceProvider'.`
> Very strange, but I get it from the latest version in the main branch.

These files exist on the main branch https://github.com/breeffy/react-native-calendar/tree/main/example/src/components/appearanceProvider. It's something with snack reproduction itself.

**Comment by Angelk90** [comment]
@likern : I can't tell you, however just drag the files and that's it, you just have to be careful on the paths.

**Comment by likern** [comment]
Expo does not work with new monorepo approach. And does not work with Storybook React Native very well.
Failed attempt is https://github.com/breeffy/react-native-monorepo/pull/79.

So neither expo nor snack will be added anytime soon.

**Comment by likern** [comment]
If anyone is willing to add expo PR is welcome.
